### ISSUE TITLE
Hi, I wanna ask how to use this?

### ISSUE THREAD

**Issue by PatrykCzyz** [jitsi/jitsi-multitrack-recorder#26]

**Comment by jmcclelland** [comment]
I'm interested as well. I see that we can use the `rerun.sh` script to launch the docker container. But I'm not sure how to configure jitsi-meet to send audio to this tool. Are their any instructions for integration with jitsi meet?

We use [Jitsi Simultaneous Interpretation](https://gitlab.com/mfmt/jsi), which manipulates the local volume of each participant to provide a live interpretation feature. But, it also means our recordings combine both the speaker and the interpreter at the same time. Having the ability to get an audio recording with each participant in a different track would allow us to produce both original language and interpretation recordings.

**Comment by bgrozev** [comment]
The jitsi-videobridge/jicofo side of this is still work in progress, you can monitor here:
https://github.com/jitsi/jitsi-videobridge/pull/2220

**Comment by jmdurant** [comment]
Hi @bgrozev and team,
I'm implementing JMR backend transcription following the bleeding-edge documentation from GitHub issue #26 and your recent comments about the new flow. I've successfully set up JMR but I'm having issues getting the frontend to trigger the backend transcription pathway instead of traditional Jigasi.  Running all this with latest/unstable docker images,  Couple of questions..
 - Frontend Configuration: Are there additional frontend configuration options needed to enable the backend transcription pathway? The current config seems to trigger traditional Jigasi instead of the new JMR flow.
- Flow Clarification: Based on your comment "the client requests transcription and jicofo enables recording" - should clicking the transcription button automatically trigger JMR recording, or is there a specific sequence needed?  with recording audio and video?
- WebSocket Endpoint: Is /record/MEETING_ID the correct JMR endpoint? I found this in the source code but want to confirm.


Current Setup
Environment:
Jitsi Version: unstable tags (built July 11, 2025 - same day)
JMR Container: jitsi/jitsi-multitrack-recorder:latest running on port 8989
All containers: Fresh bleeding-edge builds with today's date

Configuration Files:
Frontend (custom-config.js):
```
// Backend transcription configuration
config.transcription = {
    enabled: true,
    inviteJigasiOnBackendTranscribing: false,
    autoTranscribeOnRecord: true
};

config.recording = { enabled: true };

// Critical metadata flag from your PR quote
config.metadata = {
    recording: {
        isTranscribingEnabled: true
    }
};
```


Jicofo (custom-jicofo.conf):
```
jicofo {
    transcription {
        url-template = "ws://jitsi-docker_multitrack_recorder:8989/record/MEETING_ID"
    }
}
```

JMR Service (multitrack-recorder.yml):
```
services:
  jitsi-multitrack-recorder:
    image: jitsi/jitsi-multitrack-recorder:latest
    container_name: ${COMPOSE_PROJECT_NAME}_multitrack_recorder
    ports:
      - "8989:8989"
    volumes:
      - ${RECORDINGS_DIR}:/data:Z
    environment:
      - ENABLE_MULTI_TRACK=1
      - XMPP_AUTH_DOMAIN=auth.${XMPP_DOMAIN}
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${XMPP_DOMAIN}
      - XMPP_SERVER=xmpp.${XMPP_DOMAIN}
      - XMPP_DOMAIN=${XMPP_DOMAIN}
      - JVB_BREWERY_MUC=jvbbrewery@internal-muc.${XMPP_DOMAIN}
      - TZ=${TZ}
    networks:
      - meet.jitsi
```

In my .env I have:
```
ENABLE_JIGASI=1
ENABLE_TRANSCRIPTIONS=true
JIGASI_DISABLE_SIP=true
ENABLE_RECORDING=1
ENABLE_MULTI_TRACK=1
```
